version: '3'
services: 
  admin-service: 
    image: mkhang123/adminbe:latest
    volumes:
      - ./:/usr/src/app
    networks: 
      - backend
    environment:
      - MYSQL_HOST=66.42.59.144
      - MYSQL_USER=lucifer
      - MYSQL_PASS=12344321
      - MYSQL_DB=moviedb
    ports: 
      - 1111:9999
networks: 
  backend: