version: '3'
services: 
  admin-service: 
    build: ./
    image: kdev/admin-backend
    volumes:
      - ./:/usr/src/app
    networks: 
      - backend
    environment:
      - MYSQL_HOST=139.180.187.185
      - MYSQL_USER=lucifer
      - MYSQL_PASS=123123
      - MYSQL_DB=moviedb
    ports: 
      - 1111:9999
networks: 
  backend: