version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.0.1

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: kdev/admin-backend
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASS
      - run:
          name: Login
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
      - docker/build:
          image: $DOCKER_IMAGE
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER  './deploy.sh'


workflows:
  build-and-deploy:
    jobs:
      - build-and-push:
        filters:
          branches:
            only:
              - master
      - deploy:
          requires:
            - build-and-push
