version: 2.1
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.0.1

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: kdev/backend
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  build-and-deploy:
    jobs:
      - node/test
      - build-and-push
        filters:
          requires:
            - node/test
          branches:
            only:
              - master
