version: 2.1
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.0.1

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: kdev/admin-backend
      DOCKER_TAGS: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASS
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAGS
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAGS
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "38:61:fe:22:f5:10:19:c6:7d:c9:96:e9:24:2a:8b:0d"
      - run: ssh -oStrictHostKeyChecking=no root@139.180.187.185 './deploy.sh'


workflows:
  build-and-deploy:
    jobs:
      - node/test
      - build-and-push:
        requires:
            - node/test
        filters:
          branches:
            only:
              - master
      - deploy:
          requires:
            - build-and-push
