version: '3'
services: 
  mysql: 
    image: mysql
    networks: 
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_USER=lucifer
      - MYSQL_PASSWORD=123123 
      - MYSQL_DATABASE=moviedb
    expose: 
      - '3306'
    ports: 
      - 3306:3306
    cap_add:
      - SYS_NICE
    container_name: mysql-node
networks: 
  backend: